//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalisisAcademico.Web.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admisión.
        /// </summary>
        public static string Admision {
            get {
                return ResourceManager.GetString("Admision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el archivo de forma adecuada.
        /// </summary>
        public static string MES_ERROR_CREAR_ARCHIVO {
            get {
                return ResourceManager.GetString("MES_ERROR_CREAR_ARCHIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Inicio de Sesion..
        /// </summary>
        public static string MES_ERROR_LOGIN {
            get {
                return ResourceManager.GetString("MES_ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ningun archivo cargado.
        /// </summary>
        public static string MES_NINGUN_ARCHIVO_SELECCIONADO {
            get {
                return ResourceManager.GetString("MES_NINGUN_ARCHIVO_SELECCIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo fue  modificado exitosamente.
        /// </summary>
        public static string MOODIFICACION_EXITOSA {
            get {
                return ResourceManager.GetString("MOODIFICACION_EXITOSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Documentos.
        /// </summary>
        public static string RUTA_DIRECTORIO {
            get {
                return ResourceManager.GetString("RUTA_DIRECTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptada.
        /// </summary>
        public static string STATUS_ACEPTADA {
            get {
                return ResourceManager.GetString("STATUS_ACEPTADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string STATUS_CANCELADA {
            get {
                return ResourceManager.GetString("STATUS_CANCELADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denegada.
        /// </summary>
        public static string STATUS_DENEGADA {
            get {
                return ResourceManager.GetString("STATUS_DENEGADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string STATUS_INICIAL_ACTIVA {
            get {
                return ResourceManager.GetString("STATUS_INICIAL_ACTIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Proceso.
        /// </summary>
        public static string STATUS_PROCESO {
            get {
                return ResourceManager.GetString("STATUS_PROCESO", resourceCulture);
            }
        }
    }
}
